gizatechxyz/orion

src/operators/math/tensor/core.cairo, src/operators/math/tensor/helpers.cairo, src/operators/math/tensor/tensor_i32.cairo, src/operators/math/tensor/tensor_u32.cairo
Some checks are missing in the Tensor implementation.
No standard is used for comments.
- add checks
- add rust style comments
=> Tensor: Rust style comments + checks

.github/ISSUE_TEMPLATE/01_BUG_REPORT.md, .github/ISSUE_TEMPLATE/02_FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/03_CODEBASE_IMPROVEMENT.md, .github/PULL_REQUEST_TEMPLATE.md
- Currently, there is no templates for PRs and Issues.
Set up templates for PRs and Issues.
=> Issue & PR templates

src/numbers/fixed_point/types.cairo
=> remove unnecessary into that is breaking cairo-test

docs/apis/operators/tensor/tensor.new.md
=> Fix markdown content

docgen/src/main.rs, docs/apis/numbers/fixed-point/README.md, docs/apis/numbers/signed-integer/README.md, docs/apis/operators/neural-network/README.md, docs/apis/operators/neural-network/nn.leaky_relu.md, docs/apis/operators/neural-network/nn.linear.md, docs/apis/operators/neural-network/nn.relu.md, docs/apis/operators/neural-network/nn.softmax.md, docs/apis/operators/tensor/README.md, docs/apis/performance/README.md, docs/apis/performance/performance.quantize_linear.md
- links did not redirect to the right page.
-  
- fixed link redirection
-
-
=> fix links in doc

docs/CHANGELOG.md, docs/SUMMARY.md, docs/apis/compatibility.md, docs/apis/operators/tensor/tensor.abs.md, src/operators/tensor/core.cairo, src/operators/tensor/implementations/impl_tensor_fp.cairo, src/operators/tensor/implementations/impl_tensor_i32.cairo, src/operators/tensor/implementations/impl_tensor_u32.cairo, src/operators/tensor/math.cairo, src/operators/tensor/math/abs.cairo, src/operators/tensor/math/abs/abs_fp.cairo, src/operators/tensor/math/abs/abs_i32.cairo, src/operators/tensor/math/abs/abs_u32.cairo, src/tests/operators/math.cairo, src/tests/operators/math/abs.cairo, src/tests/operators/math/abs/abs_fp_test.cairo, src/tests/operators/math/abs/abs_i32_test.cairo, src/tests/operators/math/abs/abs_u32_test.cairo
Added abs tensor operator
No abs tensor operator
You can now do `tensor.abs()`
=> feat/abs: add tensor abs operator

src/numbers/signed_integer/i128.cairo, src/numbers/signed_integer/i16.cairo, src/numbers/signed_integer/i32.cairo, src/numbers/signed_integer/i64.cairo, src/numbers/signed_integer/i8.cairo
For all signed integers, `x < y` returns `true` where `x==y`
Issue Number: #76
- `x < y` returns `false` where `x == y` or `x > y`
=> fix:#76:  less than (<) operator impl fix

docs/CHANGELOG.md, docs/SUMMARY.md, docs/apis/compatibility.md, docs/apis/operators/tensor/tensor.abs.md, docs/apis/operators/tensor/tensor.ceil.md, src/operators/tensor/core.cairo, src/operators/tensor/implementations/impl_tensor_fp.cairo, src/operators/tensor/implementations/impl_tensor_i32.cairo, src/operators/tensor/implementations/impl_tensor_u32.cairo, src/operators/tensor/math.cairo, src/operators/tensor/math/ceil.cairo, src/operators/tensor/math/ceil/ceil_fp.cairo, src/operators/tensor/math/ceil/ceil_fp/core.cairo, src/operators/tensor/math/ceil/ceil_fp/fp16x16.cairo, src/operators/tensor/math/ceil/ceil_fp/fp8x23.cairo, src/operators/tensor/math/ceil/ceil_i32.cairo, src/operators/tensor/math/ceil/ceil_u32.cairo, src/tests/operators/math.cairo, src/tests/operators/math/ceil.cairo, src/tests/operators/math/ceil/ceil_fp_test.cairo, src/tests/operators/math/ceil/ceil_i32_test.cairo, src/tests/operators/math/ceil/ceil_u32_test.cairo
Added ceil tensor operator
Issue Number: #92 
You can now do `tensor.ceil()`
=> feat#92: add ceil operator

docs/CHANGELOG.md, docs/SUMMARY.md, docs/apis/compatibility.md, docs/apis/operators/tensor/tensor.argmin.md, src/operators/tensor/core.cairo, src/operators/tensor/implementations/impl_tensor_fp.cairo, src/operators/tensor/implementations/impl_tensor_i32.cairo, src/operators/tensor/implementations/impl_tensor_u32.cairo, src/operators/tensor/math.cairo, src/operators/tensor/math/argmin.cairo, src/operators/tensor/math/argmin/argmin_fp.cairo, src/operators/tensor/math/argmin/argmin_fp/core.cairo, src/operators/tensor/math/argmin/argmin_fp/fp16x16.cairo, src/operators/tensor/math/argmin/argmin_fp/fp8x23.cairo, src/operators/tensor/math/argmin/argmin_i32.cairo, src/operators/tensor/math/argmin/argmin_u32.cairo, src/tests/operators/math.cairo, src/tests/operators/math/argmin.cairo, src/tests/operators/math/argmin/argmin_fp_test.cairo, src/tests/operators/math/argmin/argmin_i32_test.cairo, src/tests/operators/math/argmin/argmin_u32_test.cairo
Added ArgMin Operator
Issue Number: #87 
- You can now do `tensor.argmin`
=> feat: add argmin operator #87

README.md
There are no informative badges in the repository `README.md`
- Added informative badges for easy access
=> feat: Add badges to README

docs/resources/tutorials/mnist-classification-with-feedforward-neural-network.md, docs/resources/tutorials/mnist-classification-with-orion.md
=> Fix: typos

docs/CHANGELOG.md, src/numbers/signed_integer/i128.cairo, src/numbers/signed_integer/i16.cairo, src/numbers/signed_integer/i32.cairo, src/numbers/signed_integer/i64.cairo, src/numbers/signed_integer/i8.cairo, src/tests/numbers/signed_integer_test.cairo
There is no way to convert Signed Integers to felt252 with Into trait.
- Add into trait to signed integers
- tests.
-
=> Feat: Convert Signed Integers to Felt252 with Into trait

docs/apis/compatibility.md
=> Merge main into dev

docs/CHANGELOG.md, docs/SUMMARY.md, docs/apis/compatibility.md, docs/apis/operators/tensor/README.md, docs/apis/operators/tensor/tensor.cumsum.md, src/operators/tensor/core.cairo, src/operators/tensor/helpers.cairo, src/operators/tensor/implementations/impl_tensor_fp.cairo, src/operators/tensor/implementations/impl_tensor_i32.cairo, src/operators/tensor/implementations/impl_tensor_u32.cairo, src/operators/tensor/math.cairo, src/operators/tensor/math/cumsum.cairo, src/operators/tensor/math/cumsum/cumsum_fp.cairo, src/operators/tensor/math/cumsum/cumsum_fp/core.cairo, src/operators/tensor/math/cumsum/cumsum_fp/fp16x16.cairo, src/operators/tensor/math/cumsum/cumsum_fp/fp8x23.cairo, src/operators/tensor/math/cumsum/cumsum_i32.cairo, src/operators/tensor/math/cumsum/cumsum_u32.cairo, src/operators/tensor/math/cumsum/helpers.cairo, src/tests/operators/tensor/math.cairo, src/tests/operators/tensor/math/cumsum.cairo, src/tests/operators/tensor/math/cumsum/cumsum_fp_test.cairo, src/tests/operators/tensor/math/cumsum/cumsum_fp_test/cumsum_fp16x16_test.cairo, src/tests/operators/tensor/math/cumsum/cumsum_fp_test/cumsum_fp8x23_test.cairo, src/tests/operators/tensor/math/cumsum/cumsum_i32_test.cairo, src/tests/operators/tensor/math/cumsum/cumsum_u32_test.cairo
Added cumsum operator
Issue Number: #97
- You can use `tensor.cumsum`
=> Added cumsum operator

.github/workflows/test.yaml, Scarb.toml
The CI uses a manual download of cairo to run the tests
Usage of Scarb CI step to automate and simplify running the test in CI
=> Add Scarb step in Github Action

Scarb.toml
I fixed compiling errors, by adding Alexandria version.
=> Add Alexandria version. 

docgen/src/main.rs, docs/SUMMARY.md, docs/framework/operators/machine-learning/xgboost-regressor/README.md, docs/framework/operators/machine-learning/xgboost-regressor/xgboost.predict.md, src/operators/ml.cairo, src/operators/ml/xgboost_regressor.cairo, src/operators/ml/xgboost_regressor/core.cairo, src/operators/ml/xgboost_regressor/implementations.cairo, src/operators/ml/xgboost_regressor/implementations/xgboost_regressor_fp16x16.cairo, src/operators/ml/xgboost_regressor/implementations/xgboost_regressor_fp32x32.cairo, src/operators/ml/xgboost_regressor/implementations/xgboost_regressor_fp64x64.cairo, src/operators/ml/xgboost_regressor/implementations/xgboost_regressor_fp8x23.cairo
Implement XGBoost regressor prediction
=> Feat: XGboostRegressor Prediction

docgen/src/main.rs, docs/SUMMARY.md, docs/framework/operators/machine-learning/tree-classifier/README.md, docs/framework/operators/machine-learning/tree-classifier/tree.predict.md, docs/framework/operators/machine-learning/tree-classifier/tree.predict_proba.md, docs/framework/operators/machine-learning/tree-regressor/tree.fit.md, docs/framework/operators/machine-learning/tree-regressor/tree.predict.md, src/operators/ml.cairo, src/operators/ml/tree_classifier.cairo, src/operators/ml/tree_classifier/core.cairo, src/operators/ml/tree_classifier/implementations.cairo, src/operators/ml/tree_classifier/implementations/tree_classifier_fp16x16.cairo, src/operators/ml/tree_classifier/implementations/tree_classifier_fp32x32.cairo, src/operators/ml/tree_classifier/implementations/tree_classifier_fp64x64.cairo, src/operators/ml/tree_classifier/implementations/tree_classifier_fp8x23.cairo, src/operators/ml/tree_regressor/core.cairo, src/operators/ml/tree_regressor/implementations/tree_regressor_fp16x16.cairo, src/operators/ml/tree_regressor/implementations/tree_regressor_fp32x32.cairo, src/operators/ml/tree_regressor/implementations/tree_regressor_fp64x64.cairo, src/operators/ml/tree_regressor/implementations/tree_regressor_fp8x23.cairo, src/operators/ml/xgboost_regressor/core.cairo, src/operators/ml/xgboost_regressor/implementations/xgboost_regressor_fp16x16.cairo, src/operators/ml/xgboost_regressor/implementations/xgboost_regressor_fp32x32.cairo, src/operators/ml/xgboost_regressor/implementations/xgboost_regressor_fp64x64.cairo, src/operators/ml/xgboost_regressor/implementations/xgboost_regressor_fp8x23.cairo
Implement `TreeClassifierTrait` prediction
=> Feat: Tree Classifier

README.md
=> Update number of contributors

docs/framework/operators/neural-network/nn.softmax.md, src/operators/nn/core.cairo
Issue Number: [434](https://github.com/gizatechxyz/orion/issues/434)
Documentation update
=> fix: incorrect type issue with softmax

nodegen/helpers.py
After the last merge, generating tests with `nodegen` throws `TypeError: get_test_refs() missing 1 required positional argument: 'is_sequence'.
`
Issue Number:  #462 
- `nodegen` works as expected
=> Fix missing argument

docgen/src/main.rs, docs/framework/numbers/fixed-point/README.md, docs/framework/operators/machine-learning/tree-ensemble-regressor/README.md, docs/framework/operators/machine-learning/tree-ensemble-regressor/tree_ensemble_regressor.predict.md, docs/framework/operators/neural-network/README.md, src/operators/ml.cairo, src/operators/ml/tree_ensemble.cairo, src/operators/ml/tree_ensemble/tree_ensemble_regressor.cairo, tests/lib.cairo, tests/ml.cairo, tests/ml/tree_ensemble_regressor.cairo
feat : TreeEnsembleRegressor
Issue Number: #498 
Implementation of the ONNX ML operator Tree Ensemble Regressor :
https://github.com/onnx/onnx/blob/main/docs/Operators-ml.md#ai.onnx.ml.TreeEnsembleRegressor
=> feat:TreeEnsembleRegressor

docgen/src/main.rs, docs/SUMMARY.md, docs/framework/operators/machine-learning/svm-classifier/README.md, docs/framework/operators/machine-learning/svm-classifier/svm_classifier.predict.md, src/operators/matrix.cairo, src/operators/ml/svm.cairo, src/operators/ml/svm/svm_classifier.cairo, src/operators/tensor/implementations/tensor_fp64x64.cairo, tests/ml.cairo, tests/ml/svm_classifier_test.cairo
Issue Number: #539 
I also modified the MutMatrixTrait to add the matrix_vector_product and changed the precision used in FP64x64TensorPartialEq.
=> feat: SVM Classifier

README.md, docs/framework/operators/neural-network/README.md, docs/framework/operators/neural-network/nn.conv.md, docs/framework/operators/neural-network/nn.conv_transpose.md, docs/framework/operators/tensor/tensor.min.md, docs/framework/operators/tensor/tensor.qlinear_add.md, docs/framework/operators/tensor/tensor.qlinear_matmul.md, docs/framework/operators/tensor/tensor.qlinear_mul.md, src/operators/nn/core.cairo, src/operators/tensor/core.cairo
Updated path to license in README. Also found some recurring typos in the docs, I fixed them in all files, including in cairo files, hopefully that was the right thing to do.
=> chore: updated path & proofreading

docgen/src/main.rs, docs/framework/operators/machine-learning/tree-ensemble/README.md, docs/framework/operators/machine-learning/tree-ensemble/tree_ensemble.predict.md, src/operators/ml.cairo, src/operators/ml/tree_ensemble.cairo, src/operators/ml/tree_ensemble/tree_ensemble.cairo, tests/lib.cairo, tests/ml.cairo, tests/ml/tree_ensemble_test.cairo
Issue Number: #575 
My implem is very different as the ONNX one for management of the trees, I'm happy to try different options if you think some other implem choices might be more optimal.
=> feat: tree ensemble
